[project]
name = "eaisi-uwv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cbsodata>=1.3.5",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.45",
]
